### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by andreytsushima** [CFSworks/ansible-routeros#1]
Hi, how to install this modules?

Thx

**Comment by CFSworks** [comment]
Hello!

The only module in the repository is `routeros_command` - my project requirements changed and stopped requiring RouterOS support before I was able to finish the full list, but you are welcome to fork and continue developing the other modules.

The work in this repository is(/was) intended for inclusion in Ansible core so it's not very easy to use standalone in an existing Ansible installation, but it is possible. See `test.sh` in the repository for how an inventory file must look and what the environment variables must be, and `ansible.cfg` for the necessary Ansible configuration flags.
